import { db } from "./db";
import { AuditAction } from "./schema";

/**
 * Logs an administrative action to the audit_log table.
 * This should be called whenever a significant change is made by an admin or system process.
 *
 * @param actorId - The ID of the user performing the action (null for system actions)
 * @param action - The type of action being performed (must be one of AuditAction)
 * @param targetType - The table or entity type being affected (e.g., 'activity', 'user')
 * @param targetId - The ID of the specific entity being affected
 * @param note - Optional additional details about the action
 */
export async function logAudit(
  actorId: number | null,
  action: AuditAction,
  targetType: string,
  targetId: number,
  note?: string
) {
  try {
    await db
      .insertInto("auditLog")
      .values({
        actorId,
        action,
        targetType,
        targetId,
        note,
        // createdAt is generated by default
      })
      .execute();
  } catch (error) {
    // We don't want to fail the main request if logging fails, but we should log the error
    console.error("Failed to write audit log:", error);
  }
}