/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ActivityStatus = "cancelled" | "closed" | "draft" | "open";

export type AdminRole = "content_admin" | "event_admin" | "super_admin";

export type AuditAction = "activity_cancelled" | "activity_checkin_toggled" | "activity_closed" | "activity_created" | "activity_updated" | "book_approved" | "book_hidden" | "book_imported" | "borrow_status_changed" | "feedback_flagged" | "feedback_published" | "feedback_retagged" | "notification_sent" | "registration_confirmed" | "topic_created" | "topic_updated" | "user_joined_date_changed" | "user_locked" | "user_role_changed" | "user_trusted_member_changed" | "user_unlocked";

export type BookStatus = "available" | "borrowed" | "unavailable";

export type BorrowStatus = "approved" | "borrowed" | "cancelled" | "completed" | "pending" | "return_requested";

export type CheckinMethod = "manual" | "qr";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type LogoType = "emoji" | "image";

export type NotificationChannel = "both" | "email" | "in_app";

export type NotificationType = "activity_cancelled" | "activity_reminder" | "admin_manual" | "borrow_approved" | "borrow_rejected" | "borrow_request" | "new_activity" | "return_confirmed" | "return_reminder" | "system_announcement";

export type RegistrationStatus = "confirmed" | "pending";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type TitleColor = "blue" | "brown" | "green" | "orange" | "purple" | "rose" | "teal";

export type UserRole = "admin" | "member";

export interface Activity {
  checkinEnabled: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  createdByAdmin: number | null;
  description: string | null;
  endTime: Timestamp | null;
  id: Generated<number>;
  imageUrl: string | null;
  location: string | null;
  maxParticipants: number | null;
  startTime: Timestamp;
  status: Generated<ActivityStatus>;
  title: string;
}

export interface ActivityAttendance {
  activityId: number;
  checkinAt: Generated<Timestamp>;
  checkinMethod: Generated<CheckinMethod>;
  id: Generated<number>;
  userId: number;
}

export interface ActivityFeedback {
  activityId: number;
  aiFlagged: Generated<boolean>;
  aiReason: string | null;
  aiSuggested: Generated<boolean>;
  comment: string | null;
  createdAt: Generated<Timestamp>;
  displayTopicId: number | null;
  id: Generated<number>;
  isAnonymous: Generated<boolean>;
  isPublished: Generated<boolean>;
  originalTopicId: number;
  publishedAt: Timestamp | null;
  rating: number;
  userId: number;
}

export interface ActivityRegistration {
  activityId: number;
  confirmedAt: Timestamp | null;
  confirmedBy: number | null;
  id: Generated<number>;
  registeredAt: Generated<Timestamp>;
  status: Generated<RegistrationStatus>;
  userId: number;
}

export interface AppBranding {
  appDescription: Generated<string | null>;
  appName: Generated<string>;
  contactEmail: Generated<string | null>;
  contactPhone: Generated<string | null>;
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  logoType: Generated<LogoType>;
  logoValue: Generated<string>;
  pageCovers: Generated<Json>;
  updatedAt: Generated<Timestamp | null>;
  updatedBy: number | null;
}

export interface AppThemeSettings {
  createdAt: Generated<Timestamp>;
  customFonts: Generated<Json>;
  darkTheme: Generated<Json>;
  id: Generated<number>;
  isActive: Generated<boolean>;
  lightTheme: Generated<Json>;
  presetName: Generated<string>;
  updatedAt: Generated<Timestamp>;
  updatedBy: number | null;
}

export interface AuditLog {
  action: AuditAction;
  actorId: number | null;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  note: string | null;
  targetId: number;
  targetType: string;
}

export interface Book {
  approvedAt: Timestamp | null;
  approvedBy: number | null;
  author: string | null;
  category: string | null;
  coverUrl: string | null;
  createdAt: Generated<Timestamp>;
  district: string | null;
  id: Generated<number>;
  isApproved: Generated<boolean | null>;
  isHidden: Generated<boolean | null>;
  ownerId: number | null;
  ownerName: string | null;
  ownerPhoneFull: string | null;
  ownerPhoneMasked: string | null;
  province: string | null;
  status: Generated<BookStatus>;
  title: string;
}

export interface BorrowRecord {
  bookId: number;
  borrowerConfirmed: Generated<boolean>;
  borrowerId: number;
  completedAt: Timestamp | null;
  completionNote: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  ownerConfirmed: Generated<boolean>;
  status: Generated<BorrowStatus>;
}

export interface FeedbackTopic {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  isActive: Generated<boolean>;
  name: string;
}

export interface LoginAttempts {
  attemptedAt: Timestamp | null;
  email: string;
  id: Generated<number>;
  success: Generated<boolean>;
}

export interface MemberTitles {
  color: TitleColor;
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  isActive: Generated<boolean>;
  isDefault: Generated<boolean>;
  name: string;
}

export interface Notification {
  channel: Generated<NotificationChannel>;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  isImportant: Generated<boolean>;
  isRead: Generated<boolean>;
  link: string | null;
  message: string;
  relatedId: number | null;
  relatedType: string | null;
  sentByAdmin: number | null;
  title: string;
  type: NotificationType;
  userId: number;
}

export interface NotificationBatch {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  link: string | null;
  message: string;
  recipientCount: Generated<number>;
  sentByAdmin: number;
  targetFilter: Json | null;
  targetType: Generated<string>;
  title: string;
}

export interface OauthAccounts {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  provider: string;
  providerEmail: string | null;
  providerUserId: string;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface OauthStates {
  codeVerifier: string;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<number>;
  provider: string;
  redirectUrl: string;
  state: string;
}

export interface PublishSettings {
  id: Generated<number>;
  settingKey: string;
  settingValue: number;
  updatedAt: Generated<Timestamp>;
  updatedBy: number | null;
}

export interface Sessions {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp>;
  userId: number;
}

export interface UserNotificationSettings {
  emailEnabled: Generated<boolean>;
  id: Generated<number>;
  inAppEnabled: Generated<boolean>;
  quietHoursEnabled: Generated<boolean>;
  quietHoursEnd: Generated<string | null>;
  quietHoursStart: Generated<string | null>;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  passwordHash: string;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface Users {
  adminRole: AdminRole | null;
  avatarUrl: string | null;
  createdAt: Generated<Timestamp>;
  district: string | null;
  email: string;
  fullName: string;
  googleId: string | null;
  id: Generated<number>;
  isActive: Generated<boolean>;
  isTrustedMember: Generated<boolean>;
  joinedAt: Generated<Timestamp>;
  joinedAtUpdatedByMember: Generated<boolean>;
  lastLoginAt: Timestamp | null;
  lockReason: string | null;
  province: string | null;
  role: Generated<UserRole>;
  updatedAt: Generated<Timestamp>;
}

export interface UserTitles {
  assignedAt: Generated<Timestamp>;
  assignedBy: number | null;
  id: Generated<number>;
  titleId: number;
  userId: number;
}

export interface DB {
  activity: Activity;
  activityAttendance: ActivityAttendance;
  activityFeedback: ActivityFeedback;
  activityRegistration: ActivityRegistration;
  appBranding: AppBranding;
  appThemeSettings: AppThemeSettings;
  auditLog: AuditLog;
  book: Book;
  borrowRecord: BorrowRecord;
  feedbackTopic: FeedbackTopic;
  loginAttempts: LoginAttempts;
  memberTitles: MemberTitles;
  notification: Notification;
  notificationBatch: NotificationBatch;
  oauthAccounts: OauthAccounts;
  oauthStates: OauthStates;
  publishSettings: PublishSettings;
  sessions: Sessions;
  userNotificationSettings: UserNotificationSettings;
  userPasswords: UserPasswords;
  users: Users;
  userTitles: UserTitles;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const ActivityStatusArrayValues: [ActivityStatus, ...ActivityStatus[]] = ["cancelled","closed","draft","open"];
export const BookStatusArrayValues: [BookStatus, ...BookStatus[]] = ["available","borrowed","unavailable"];
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin","member"];
export const AdminRoleArrayValues: [AdminRole, ...AdminRole[]] = ["content_admin","event_admin","super_admin"];
export const CheckinMethodArrayValues: [CheckinMethod, ...CheckinMethod[]] = ["manual","qr"];
export const AuditActionArrayValues: [AuditAction, ...AuditAction[]] = ["activity_cancelled","activity_checkin_toggled","activity_closed","activity_created","activity_updated","book_approved","book_hidden","book_imported","borrow_status_changed","feedback_flagged","feedback_published","feedback_retagged","notification_sent","registration_confirmed","topic_created","topic_updated","user_joined_date_changed","user_locked","user_role_changed","user_trusted_member_changed","user_unlocked"];
export const BorrowStatusArrayValues: [BorrowStatus, ...BorrowStatus[]] = ["approved","borrowed","cancelled","completed","pending","return_requested"];
export const NotificationChannelArrayValues: [NotificationChannel, ...NotificationChannel[]] = ["both","email","in_app"];
export const NotificationTypeArrayValues: [NotificationType, ...NotificationType[]] = ["activity_cancelled","activity_reminder","admin_manual","borrow_approved","borrow_rejected","borrow_request","new_activity","return_confirmed","return_reminder","system_announcement"];
export const RegistrationStatusArrayValues: [RegistrationStatus, ...RegistrationStatus[]] = ["confirmed","pending"];
export const LogoTypeArrayValues: [LogoType, ...LogoType[]] = ["emoji","image"];
export const TitleColorArrayValues: [TitleColor, ...TitleColor[]] = ["blue","brown","green","orange","purple","rose","teal"];
// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.